@startuml view_major_details
!theme plain
hide footbox

actor Client
participant ":MajorController" as Controller
participant ":MajorService" as Service
participant ":MajorRepository" as Repository
participant "Database" as DB

' --- MAIN FLOW ---
Client -> Controller: GET /api/v1/majors/{id}
activate Controller

Controller -> Service: findById(id)
activate Service

Service -> Repository: findMajorDTOById(id)
activate Repository

Repository -> DB: Query Major by ID with Subject Count
activate DB
DB --> Repository: MajorDTO / Null
deactivate DB

Repository --> Service: Optional<MajorDTO>
deactivate Repository

alt Major not found
    Service -->> Controller: <<throw>> ResourceNotFoundException
    Controller --> Client: 404 Not Found
end

Service --> Controller: MajorDTO
deactivate Service

Controller --> Client: 200 OK
deactivate Controller

@enduml
