@startuml Create Major - Class Diagram
!theme plain
skinparam classAttributeIconSize 0
hide circle
skinparam circledCharacterRadius 0

class MajorController {
  - majorService : MajorService
  + create(request : MajorCreateRequest) : Response<MajorDTO>
}

class MajorService {
  - majorRepository : MajorRepository
  - majorMapper : MajorMapper
  + create(request : MajorCreateRequest) : MajorDTO
}

interface MajorRepository <<interface>> {
  + existsByCode(code : String) : boolean
  + existsByName(name : String) : boolean
  + save(entity : Major) : Major
}

interface MajorMapper <<interface>> {
  + toEntity(request : MajorCreateRequest) : Major
  + toDTO(entity : Major) : MajorDTO
}

class Major {
  - id : Short
  - name : String
  - code : String
  - subjects : Set<Subject>
  - studentProfiles : Set<StudentProfile>
}

class BaseEntity {
  - isActive : Boolean
  - createdAt : Instant
  - updatedAt : Instant
}

class MajorCreateRequest {
  - name : String
  - code : String
}

class MajorDTO {
  - id : Short
  - name : String
  - code : String
  - totalSubject : Integer
}

class BaseDTO {
  - isActive : Boolean
  - createdAt : Instant
  - updatedAt : Instant
}

class Response<T> {
  - status : int
  - message : String
  - code : String
  - data : T
}

MajorController --> MajorService
MajorService --> MajorRepository
MajorService --> MajorMapper

MajorController ..> Response : <<use>>
MajorController ..> MajorDTO : <<use>>
MajorController ..> MajorCreateRequest : <<use>>
MajorService ..> Major : <<use>>
MajorService ..> MajorDTO : <<use>>
MajorService ..> MajorCreateRequest : <<use>>
MajorRepository ..> Major : <<use>>
MajorMapper ..> Major : <<use>>
MajorMapper ..> MajorDTO : <<use>>
MajorMapper ..> MajorCreateRequest : <<use>>

Major --|> BaseEntity
MajorDTO --|> BaseDTO

@enduml
